[package]
name = "visard"
version = "0.1.0"
authors = ["Eric Norman <eric.norman98@hotmail.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
